import React from "react";
import "./App.scss";
import { useGet } from "restful-react";
import bitcoinGif from "./bitcoin.gif";

type Company =
  | "MSTR"
  | "SQ"
  | "TSLA"
  | "MARA"
  | "RIOT"
  | "SEETEE"
  | "COIN"
  | "MELI"
  | "GLOB"
  | "TYO:3659";

const ownership: { [key in Company]: number } = {
  MSTR: 0.92,
  TSLA: 0.73,
  MARA: 0.61,
  /**
   * https://proff.no/aksjon%C3%A6rer/bedrift/aker-capital-as/986733884
   */
  SEETEE: 4.426,
  SQ: 0.44,
  RIOT: 0.44,
  "TYO:3659": 0.54,
  MELI: 0.77,
  COIN: 0.01,
  GLOB: 0.94,
};

const Companies = Object.keys(ownership) as Company[];
const norwegianCount = 5_402_171;
const closingQ12021BTCUSD = 58_763;

const bitcoinCount: { [key in Company]: number } = {
  MSTR: 129_218,
  /**
   * Feb. 28 2022, investment fund + generated by ops
   */
  MARA: 8_956,
  COIN: 4_487,
  /**
   * Jan. 31 2022
   */
  RIOT: 5_347,
  SQ: 8_027,
  TSLA: 38_202,
  SEETEE: 1_170,
  "TYO:3659": 1_717,
  MELI: 7_800_000 / closingQ12021BTCUSD,
  GLOB: 500_000 / closingQ12021BTCUSD,
};

const companyBitcoinLinks: { [key in Company]: string } = {
  TSLA: "https://www.sec.gov/Archives/edgar/data/1318605/000156459021004599/tsla-10k_20201231.htm",
  COIN: "https://twitter.com/lawmaster/status/1364919798682034177?s=20&t=8dejGy5chq8C2PyRREgAUw",
  MARA: "https://ir.marathondh.com/news-events/press-releases/detail/1277/marathon-digital-holdings-reports-fourth-quarter-and-fiscal",
  RIOT: "https://www.riotblockchain.com/investors/news-events/press-releases/detail/123/riot-blockchain-announces-january-production-and-operations",
  MSTR: "https://ir.microstrategy.com/news-releases/news-release-details/microstrategy-adopts-bitcoin-primary-treasury-reserve-asset",
  SEETEE:
    "https://www.seetee.io/static/shareholder_letter-6ae7e85717c28831bf1c0eca1d632722.pdf",
  SQ: "https://images.ctfassets.net/2d5q1td6cyxq/5sXNrlEh2mEnTvvhgtYOm2/737bcfdc15e2a1c3cbd9b9451710ce54/Square_Inc._Bitcoin_Investment_Whitepaper.pdf",
  "TYO:3659": "https://pdf.irpocket.com/C3659/bxTh/SDDC/wbxu.pdf",
  MELI: "https://www.sec.gov/Archives/edgar/data/0001099590/000156276221000190/meli-20210505xex99_1.htm",
  GLOB: "https://www.sec.gov/Archives/edgar/data/1557860/000110465921071235/tm2116803d1_ex99-1.htm",
};

const companyNames: { [key in Company]: string } = {
  MSTR: "MicroStrategy",
  COIN: "Coinbase",
  MARA: "Marathon Digital Holdings",
  RIOT: "Riot Blockchain",
  SEETEE: "Seetee (parent Aker group)",
  SQ: "Square",
  TSLA: "Tesla",
  "TYO:3659": "Nexon",
  MELI: "MercadoLibre",
  GLOB: "Globant",
};

const indirectBtc = (company: Company) => {
  return bitcoinCount[company] * (ownership[company] / 100);
};

interface Response {
  BtcUsd: number;
}

const CompanyPercentage: React.FC<{ company: Company }> = ({
  company,
  children,
}) => (
  <>
    <a href={companyBitcoinLinks[company]}>{children}</a>{" "}
    <span className="percentage-details">
      <span className="hidden-mobile">{ownership[company].toFixed(2)}%</span>
      <span>
        {(bitcoinCount[company] * (ownership[company] / 100)).toFixed(2)} BTC
      </span>
    </span>
  </>
);

function getUpdatedAt(): Date | undefined {
  const { REACT_APP_UPDATE_DATE: rawUpdatedAt } = process.env;
  if (!rawUpdatedAt) {
    console.log("updated at: empty REACT_APP_UPDATE_DATE");
    return;
  }

  const parsed = Number.parseInt(rawUpdatedAt);
  if (Number.isNaN(parsed)) {
    console.log("updated at: NaN:", rawUpdatedAt);
    return;
  }

  return new Date(parsed * 1000);
}

function App() {
  const { data, error } = useGet<Response>("https://api.rogstad.io/oilfund");
  if (error) {
    return <p>{error.message}</p>;
  }

  if (!data) {
    return null;
  }

  const { BtcUsd } = data;

  const allBitcoins = Companies.map(indirectBtc).reduce(
    (sum, count) => sum + count
  );

  const satoshisPerCitizen = (
    (allBitcoins * 100_000_000) /
    norwegianCount
  ).toLocaleString(undefined, {
    maximumFractionDigits: 0,
  });

  const usdValueOfAllCoins = allBitcoins * BtcUsd;

  const updatedAt = getUpdatedAt();
  return (
    <>
      <img alt="bitcoin-gif" src={bitcoinGif} />
      <p id="btc-summary">
        The Norwegian government indirectly owns{" "}
        <span className="amt-btc">{allBitcoins.toFixed(2)} bitcoin</span> (~USD{" "}
        {(usdValueOfAllCoins / 1_000_000).toFixed(1)}m) through their
        international and domestic pension funds. This is equivalent to{" "}
        <span className="amt-btc">{satoshisPerCitizen} sats</span> per Norwegian
        citizen.
      </p>
      <p id="company-list">
        Companies, with<span className="hidden-mobile"> equity and</span>{" "}
        bitcoin indirectly held by the Norwegian government
        <ul>
          {Companies.map((company) => (
            <li key={company}>
              <span className="li-content">
                <CompanyPercentage company={company}>
                  {companyNames[company]}
                </CompanyPercentage>
              </span>
            </li>
          ))}
        </ul>
      </p>
      <p>
        Every once in a while a new publicly listed company succumbs to the
        bitcoin black hole. Check back here for continuously up-to-date numbers.
      </p>
      <details>
        <summary>Assumptions used to calculate BTC amounts</summary>
        <p>
          The TSLA bitcoin count is based on an estimate, where we assume they
          bought through January 2021, with a BTCUSD volume weighted average
          price (VWAP) of ${(34_840).toLocaleString()}. TSLA later sold BTC
          worth USD 272 million, and assuming their reported BTC balance sheet
          is reported at cost price, we then end up with a stack of{" "}
          {(38_202).toLocaleString()} BTC.
        </p>
        <p>
          MELI acquired BTC for USD 7.8 million, without providing any further
          details. Until they do so, we assume they bought at closing of Q1
          2021: ${closingQ12021BTCUSD.toLocaleString()}
        </p>
        <p>
          GLOB acquired BTC for USD 500 000, without providing any further
          details. Until they do so, we assume they bought at closing of Q1
          2021: ${closingQ12021BTCUSD.toLocaleString()}
        </p>
      </details>
      <p id="made-by">
        Made by <a href="https://twitter.com/torkelrogstad">Torkel Rogstad</a>,
        originally reported on by{" "}
        <a href="https://research.arcane.no/news/the-norwegian-oil-fund-now-owns-almost-600-bitcoins">
          Arcane Research
        </a>
      </p>
      {updatedAt && (
        <p id="updated-at">
          Bitcoin holdings were last updated at {updatedAt.toLocaleDateString()}
        </p>
      )}
    </>
  );
}

export default App;
